cloudinary.cloud_name=dgdjc9gdh
cloudinary.api_key=325442679113853
cloudinary.api_secret=_d3VUQwXX280i3QnDYsLmYnkmFQ
spring.datasource.url=jdbc:postgresql://localhost:5432/Placement_DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
app.jwt.secret=PLACEMENT_DRIVE_MANAGEMENT_SYSTEM_JWT_SECRET_WITH_LONG_TEXT
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
superadmin.email=superAdmin@anits.edu.in
superadmin.password=superAdmin@123
superadmin.name=ANITS
